export const EDIT_MAIN = 'EDIT_MAIN';
export const DELETE_MAIN = 'DELETE_MAIN';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';

export const STORE_CUSTOM_ORDER = 'STORE_CUSTOM_ORDER';
export const ADD_REMOVE_FAVOURITE = 'ADD_REMOVE_FAVOURITE';
export const STORE_DELIVERY = 'STORE_DELIVERY';
export const FETCH_POPULAR = 'FETCH_POPULAR'