export const EDIT_MAIN = "EDIT_MAIN";
export const DELETE_MAIN = "DELETE_MAIN";
export const REPLACE_MAIN = "REPLACE_MAIN";

export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_INGREDIENTS_FAILED = "SET_INGREDIENTS_FAILED";

export const SET_DIRECTIONS = "SET_DIRECTIONS";
export const SET_DIRECTIONS_FAILED = "SET_DIRECTIONS_FAILED";

export const SET_POPULAR = "SET_POPULAR";
export const SET_POPULAR_FAILED = "SET_POPULAR_FAILED";

export const SET_TOP_WEEK = "SET_TOP_WEEK";
export const SET_TOP_WEEK_FAILED = "SET_TOP_WEEK_FAILED";

export const INIT_TOP_WEEK_INDIV = "INIT_TOP_WEEK_INDIV";
export const SET_TOP_WEEK_INDIV_SUCCESS = "SET_TOP_WEEK_INDIV_SUCCESS";
export const SET_TOP_WEEK_INDIV_FAILURE = "SET_TOP_WEEK_INDIV_FAILURE";

export const SET_FAVOURITES = "SET_FAVOURITES";
export const SET_FAVOURITES_FAILED = "SET_FAVOURITES_FAILED";
export const ADD_REMOVE_FAVOURITE = "ADD_REMOVE_FAVOURITE";
export const UPDATE_FAVOURITES_LOCAL = "UPDATE_FAVOURITES_LOCAL";

export const POST_FAVOURITES_SUCCES = "POST_FAVOURITES_SUCCESS";
export const POST_FAVOURITES_FAILED = "POST_FAVOURITES_FAILED";

export const STORE_CUSTOM_ORDER = "STORE_CUSTOM_ORDER";
export const STORE_DELIVERY = "STORE_DELIVERY";

export const PURCHASE_ORDER_START = "PURCHASE_ORDER_START";
export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";
export const PURCHASE_ORDER_FAILED = "PURCHASE_ORDER_FAILED";

export const SET_MYORDERS_START = "SET_MYORDERS_START";
export const SET_MYORDERS_SUCCESS = "SET_MYORDERS_SUCCESS";
export const SET_MYORDERS_FAIL = "SET_MYORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REDIRECT = "AUTH_REDIRECT";
